sudo: false
language: minimal

branches:
  only:
    - /^[vV]?\d+\.\d+(\.\d+)?-\S*$/

jobs:
  include:

    - stage: alpha
      before_script: curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
      script: bash release.sh -w 0

    - stage: beta
      before_script: curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
      script: bash release.sh -w 0

    - stage: release
      before_script: curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
      script: bash release.sh

stages:
  - name: alpha
    if: branch =~ /^[vV]?\d+\.\d+(\.\d+)?-alpha(\S*)?$/
  - name: beta
    if: branch =~ /^[vV]?\d+\.\d+(\.\d+)?-beta(\S*)?$/
  - name: release
    if: branch =~ /^[vV]?\d+\.\d+(\.\d+)?-release(\S*)?$/
