sudo: false
language: minimal

jobs:
  include:

    - stage: alpha
      branches:
        only:
        - /^[vV]?\d+\.\d+(\.\d+)?-alpha(\S*)?$/
      before_script: curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
      script: bash release.sh -w 0

    - stage: beta
      branches:
        only:
        - /^[vV]?\d+\.\d+(\.\d+)?-beta(\S*)?$/
      before_script: curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
      script: bash release.sh -w 0

    - stage: release
      branches:
        only:
        - /^[vV]?\d+\.\d+(\.\d+)?-release(\S*)?$/
      before_script: curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
      script: bash release.sh

stages:
  - alpha
  - beta
  - release
